PATTERNS = [
    {
        "id": "brute-force-ssh",
        "name": "SSH Brute Force",
        "description": "Detects repeated failed SSH login attempts from a single source, indicating a brute force attack against SSH.",
        "category": "credential-access",
        "search_terms": '"Failed password"',
        "index": "main",
        "earliest": "-1h",
        "severity": "high",
        "mitre_techniques": ["T1110.001", "T1021.004"],
    },
    {
        "id": "successful-login-after-failures",
        "name": "Successful Login After Brute Force",
        "description": "Detects a successful login preceded by multiple failures from the same IP — a classic brute force success pattern.",
        "category": "credential-access",
        "search_terms": '"Accepted password"',
        "index": "main",
        "earliest": "-1h",
        "severity": "critical",
        "mitre_techniques": ["T1110.001", "T1078"],
    },
    {
        "id": "privilege-escalation-sudo",
        "name": "Sudo Privilege Escalation",
        "description": "Detects sudo usage that may indicate privilege escalation attempts by compromised or malicious users.",
        "category": "privilege-escalation",
        "search_terms": "sudo",
        "index": "main",
        "earliest": "-1h",
        "severity": "high",
        "mitre_techniques": ["T1548.003"],
    },
    {
        "id": "root-command-execution",
        "name": "Root Command Execution",
        "description": "Detects commands executed as root, particularly after a user escalated privileges.",
        "category": "privilege-escalation",
        "search_terms": '"session opened for user root"',
        "index": "main",
        "earliest": "-1h",
        "severity": "critical",
        "mitre_techniques": ["T1548.003", "T1059"],
    },
    {
        "id": "invalid-user-login",
        "name": "Invalid User Login Attempts",
        "description": "Detects login attempts targeting non-existent user accounts — common in automated credential stuffing attacks.",
        "category": "credential-access",
        "search_terms": '"invalid user"',
        "index": "main",
        "earliest": "-2h",
        "severity": "medium",
        "mitre_techniques": ["T1110.004", "T1078.003"],
    },
    {
        "id": "new-ssh-connection",
        "name": "New SSH Session Established",
        "description": "Tracks all new SSH sessions being opened, useful for detecting lateral movement or unexpected remote access.",
        "category": "lateral-movement",
        "search_terms": '"session opened for user"',
        "index": "main",
        "earliest": "-1h",
        "severity": "medium",
        "mitre_techniques": ["T1021.004"],
    },
    {
        "id": "lateral-movement-detection",
        "name": "Lateral Movement via SSH",
        "description": "Detects SSH connections between internal hosts that may indicate an attacker pivoting through the network.",
        "category": "lateral-movement",
        "search_terms": '"Accepted publickey"',
        "index": "main",
        "earliest": "-2h",
        "severity": "high",
        "mitre_techniques": ["T1021.004", "T1563.001"],
    },
    {
        "id": "log-clearing",
        "name": "Log Clearing / Tampering",
        "description": "Detects attempts to clear or manipulate system logs, a common attacker anti-forensics technique.",
        "category": "defense-evasion",
        "search_terms": '"wtmp" OR "btmp" OR "auth.log"',
        "index": "main",
        "earliest": "-4h",
        "severity": "critical",
        "mitre_techniques": ["T1070.001", "T1070.002"],
    },
    {
        "id": "cron-persistence",
        "name": "Cron Job Persistence",
        "description": "Detects cron job creation or modification that may indicate an attacker establishing persistent access.",
        "category": "persistence",
        "search_terms": "cron",
        "index": "main",
        "earliest": "-4h",
        "severity": "medium",
        "mitre_techniques": ["T1053.003"],
    },
    {
        "id": "port-scan-detection",
        "name": "Port Scan / Reconnaissance",
        "description": "Detects connection attempts across multiple ports from a single source, indicating network reconnaissance.",
        "category": "reconnaissance",
        "search_terms": '"Connection closed" OR "Connection reset"',
        "index": "main",
        "earliest": "-30m",
        "severity": "low",
        "mitre_techniques": ["T1046"],
    },
    {
        "id": "new-user-created",
        "name": "New User Account Created",
        "description": "Detects creation of new user accounts, which may indicate attacker persistence or privilege escalation.",
        "category": "persistence",
        "search_terms": '"new user" OR "useradd" OR "adduser"',
        "index": "main",
        "earliest": "-24h",
        "severity": "high",
        "mitre_techniques": ["T1136.001"],
    },
    {
        "id": "failed-su-attempts",
        "name": "Failed su Attempts",
        "description": "Detects failed attempts to switch user context via su, indicating possible privilege escalation probing.",
        "category": "privilege-escalation",
        "search_terms": '"FAILED su"',
        "index": "main",
        "earliest": "-1h",
        "severity": "medium",
        "mitre_techniques": ["T1548"],
    },
]