PATTERNS = [
    # ─── Credential Access ────────────────────────────────────────────────
    {
        "id": "brute-force-ssh",
        "name": "SSH Brute Force",
        "description": "Detects repeated failed SSH login attempts from a single source, indicating a brute force attack against SSH.",
        "category": "credential-access",
        "search_terms": '"Failed password"',
        "index": "main",
        "earliest": "-1h",
        "severity": "high",
        "mitre_techniques": ["T1110.001", "T1021.004"],
    },
    {
        "id": "successful-login-after-failures",
        "name": "Successful Login After Brute Force",
        "description": "Detects a successful login preceded by multiple failures from the same IP — a classic brute force success pattern.",
        "category": "credential-access",
        "search_terms": '"Accepted password"',
        "index": "main",
        "earliest": "-1h",
        "severity": "critical",
        "mitre_techniques": ["T1110.001", "T1078"],
    },
    {
        "id": "invalid-user-login",
        "name": "Invalid User Login Attempts",
        "description": "Detects login attempts targeting non-existent user accounts — common in automated credential stuffing attacks.",
        "category": "credential-access",
        "search_terms": '"invalid user"',
        "index": "main",
        "earliest": "-2h",
        "severity": "medium",
        "mitre_techniques": ["T1110.004", "T1078.003"],
    },
    {
        "id": "failed-su-attempts",
        "name": "Failed su Attempts",
        "description": "Detects failed attempts to switch user context via su, indicating possible privilege escalation probing.",
        "category": "credential-access",
        "search_terms": '"FAILED su"',
        "index": "main",
        "earliest": "-1h",
        "severity": "medium",
        "mitre_techniques": ["T1548"],
    },

    # ─── Privilege Escalation ─────────────────────────────────────────────
    {
        "id": "privilege-escalation-sudo",
        "name": "Sudo Privilege Escalation",
        "description": "Detects sudo usage that may indicate privilege escalation attempts by compromised or malicious users.",
        "category": "privilege-escalation",
        "search_terms": "sudo",
        "index": "main",
        "earliest": "-1h",
        "severity": "high",
        "mitre_techniques": ["T1548.003"],
    },
    {
        "id": "root-command-execution",
        "name": "Root Session Opened",
        "description": "Detects sessions opened as root, particularly after a user escalated privileges.",
        "category": "privilege-escalation",
        "search_terms": '"session opened for user root"',
        "index": "main",
        "earliest": "-1h",
        "severity": "critical",
        "mitre_techniques": ["T1548.003", "T1059"],
    },
    {
        "id": "new-user-created",
        "name": "New User Account Created",
        "description": "Detects creation of new user accounts, which may indicate attacker persistence or privilege escalation.",
        "category": "privilege-escalation",
        "search_terms": '"new user" OR "useradd" OR "adduser"',
        "index": "main",
        "earliest": "-24h",
        "severity": "high",
        "mitre_techniques": ["T1136.001"],
    },

    # ─── Lateral Movement ─────────────────────────────────────────────────
    {
        "id": "new-ssh-connection",
        "name": "New SSH Session Established",
        "description": "Tracks all new SSH sessions being opened, useful for detecting lateral movement or unexpected remote access.",
        "category": "lateral-movement",
        "search_terms": '"session opened for user"',
        "index": "main",
        "earliest": "-1h",
        "severity": "medium",
        "mitre_techniques": ["T1021.004"],
    },
    {
        "id": "lateral-movement-pubkey",
        "name": "SSH Public Key Authentication",
        "description": "Detects SSH connections using public key auth between internal hosts — may indicate an attacker pivoting with stolen keys.",
        "category": "lateral-movement",
        "search_terms": '"Accepted publickey"',
        "index": "main",
        "earliest": "-2h",
        "severity": "high",
        "mitre_techniques": ["T1021.004", "T1563.001"],
    },

    # ─── Persistence ──────────────────────────────────────────────────────
    {
        "id": "cron-persistence",
        "name": "Cron Job Persistence",
        "description": "Detects cron job creation or modification that may indicate an attacker establishing persistent access.",
        "category": "persistence",
        "search_terms": "cron",
        "index": "main",
        "earliest": "-4h",
        "severity": "medium",
        "mitre_techniques": ["T1053.003"],
    },

    # ─── Defense Evasion ──────────────────────────────────────────────────
    {
        "id": "log-clearing",
        "name": "Log Clearing / Tampering",
        "description": "Detects attempts to clear or manipulate system logs, a common attacker anti-forensics technique.",
        "category": "defense-evasion",
        "search_terms": '"wtmp" OR "btmp" OR "auth.log"',
        "index": "main",
        "earliest": "-4h",
        "severity": "critical",
        "mitre_techniques": ["T1070.001", "T1070.002"],
    },

    # ─── Reconnaissance ───────────────────────────────────────────────────
    {
        "id": "port-scan-detection",
        "name": "Port Scan / Reconnaissance",
        "description": "Detects connection attempts across multiple ports from a single source, indicating network reconnaissance.",
        "category": "reconnaissance",
        "search_terms": '"Connection closed" OR "Connection reset"',
        "index": "main",
        "earliest": "-30m",
        "severity": "low",
        "mitre_techniques": ["T1046"],
    },

    # ─── EDR Evasion Hunts ────────────────────────────────────────────────
    {
        "id": "edr-encoded-commands",
        "name": "Encoded / Obfuscated Commands",
        "description": "Hunts for base64 encoded commands or obfuscated execution strings commonly used to bypass EDR signature detection. Look for -enc, -encodedcommand, or long base64 strings in process arguments.",
        "category": "edr-evasion",
        "search_terms": '"encodedcommand" OR " -enc " OR "base64"',
        "index": "main",
        "earliest": "-2h",
        "severity": "critical",
        "mitre_techniques": ["T1027", "T1059.001"],
    },
    {
        "id": "edr-lolbin-download",
        "name": "LOLBin Download / Execution",
        "description": "Hunts for living-off-the-land binaries used to download or execute payloads: certutil, mshta, regsvr32, wmic, bitsadmin, rundll32. Legitimate tools abused to evade application whitelisting.",
        "category": "edr-evasion",
        "search_terms": '"certutil" OR "mshta" OR "regsvr32" OR "bitsadmin" OR "wmic"',
        "index": "main",
        "earliest": "-2h",
        "severity": "high",
        "mitre_techniques": ["T1218", "T1105", "T1197"],
    },
    {
        "id": "edr-process-injection",
        "name": "Process Injection Indicators",
        "description": "Hunts for signs of process injection or hollowing — unusual parent-child process relationships, ptrace calls, or /proc/*/mem access on Linux. Common EDR bypass via injecting into trusted processes.",
        "category": "edr-evasion",
        "search_terms": '"ptrace" OR "/proc/" OR "process_vm_writev" OR "LD_PRELOAD"',
        "index": "main",
        "earliest": "-2h",
        "severity": "critical",
        "mitre_techniques": ["T1055", "T1055.001", "T1055.012"],
    },
    {
        "id": "edr-ld-preload",
        "name": "LD_PRELOAD Hijacking",
        "description": "Hunts for LD_PRELOAD environment variable abuse — a classic Linux technique to inject malicious shared libraries into processes, bypassing EDR hooks by intercepting system calls before they reach the kernel.",
        "category": "edr-evasion",
        "search_terms": '"LD_PRELOAD" OR "ld.so.preload"',
        "index": "main",
        "earliest": "-4h",
        "severity": "critical",
        "mitre_techniques": ["T1574.006"],
    },
    {
        "id": "edr-timestomping",
        "name": "Timestomping / File Attribute Modification",
        "description": "Hunts for use of touch, debugfs, or similar utilities to modify file timestamps — used to hide malware by making it appear older than the intrusion date, defeating timeline-based forensics.",
        "category": "edr-evasion",
        "search_terms": '"touch -t" OR "debugfs" OR "timestomp"',
        "index": "main",
        "earliest": "-4h",
        "severity": "high",
        "mitre_techniques": ["T1070.006"],
    },
    {
        "id": "edr-rootkit-indicators",
        "name": "Rootkit / Kernel Module Loading",
        "description": "Hunts for suspicious kernel module loading (insmod, modprobe) that may indicate rootkit installation. Kernel rootkits bypass EDR entirely by operating below the OS level.",
        "category": "edr-evasion",
        "search_terms": '"insmod" OR "modprobe" OR "rmmod" OR "/dev/kmem"',
        "index": "main",
        "earliest": "-4h",
        "severity": "critical",
        "mitre_techniques": ["T1547.006", "T1014"],
    },
    {
        "id": "edr-credential-dumping-linux",
        "name": "Linux Credential Dumping",
        "description": "Hunts for attempts to access /etc/shadow, /etc/passwd, or credential-related files. Also looks for use of mimipenguin, LaZagne, or similar Linux credential dumping tools.",
        "category": "edr-evasion",
        "search_terms": '"/etc/shadow" OR "mimipenguin" OR "lazagne" OR "/etc/passwd"',
        "index": "main",
        "earliest": "-2h",
        "severity": "critical",
        "mitre_techniques": ["T1003.008", "T1552.001"],
    },
    {
        "id": "edr-container-escape",
        "name": "Container Escape Indicators",
        "description": "Hunts for container escape techniques: access to host /proc, docker socket, privileged mode abuse, or cgroup v1 notify_on_release. Used to break out of containerized environments to reach the host.",
        "category": "edr-evasion",
        "search_terms": '"docker.sock" OR "notify_on_release" OR "/proc/1/environ" OR "nsenter"',
        "index": "main",
        "earliest": "-2h",
        "severity": "critical",
        "mitre_techniques": ["T1611"],
    },
    {
        "id": "edr-defense-tool-tampering",
        "name": "Security Tool Tampering",
        "description": "Hunts for attempts to stop, disable, or uninstall security tools — antivirus, EDR agents, auditd, syslog. A key indicator of an attacker trying to blind your defenses before executing the main payload.",
        "category": "edr-evasion",
        "search_terms": '"auditd" OR "systemctl stop" OR "service stop" OR "pkill" OR "killall"',
        "index": "main",
        "earliest": "-2h",
        "severity": "critical",
        "mitre_techniques": ["T1562.001", "T1562.004"],
    },
]